stages:
    - debug
    - release
    - deliver
    - trigger

debug:
    stage: debug
    script:
        - ./build debug
    except:
        - master 

release:
    stage: release
    script:
        - ./build release
    except:
        - master 

delivery:
    stage: deliver
    variables:
        MIU_PATH: "/opt/staging/miu"
        INC_PATH: "$MIU_PATH/include"
        DBG_PATH: "$MIU_PATH/lib-dbg"
        REL_PATH: "$MIU_PATH/lib-rel"
        UT_PATH: "$MIU_PATH/unittest"
    script:
        - ./build debug
        - ./build release

        - mkdir -p $INC_PATH
        - rm -fr $INC_PATH/log
        - cp -frv ./include/log $INC_PATH

        - mkdir -p $DBG_PATH
        - cp -fv debug/liblog.a $DBG_PATH

        - mkdir -p $REL_PATH
        - cp -fv release/liblog.a $REL_PATH

        - mkdir -p $UT_PATH
        - cp -fv release/ut_log $UT_PATH
    only:
        - master 

cfg:
    stage: trigger
    script:
        - curl -X POST -F token=cbac0f405c70de287c801e2a75132d -F ref=master $GITLAB_URL/api/v4/projects/10/trigger/pipeline
    only:
        - master 
